const places = [
    {
        title: "Road cycling",
        price: "From: 1,545€/person",
        duration: "7 days / 6 nights",
        difficulty: "Moderate to Challenging.",
        smallDescription: "Tackle the French Alps on two wheels, from iconic Alpe d'Huez switchbacks to lesser-traveled Col de Sarenne, following Tour de France champions.",
        description: "Road cycling in the French Alps offers a unique challenge for cycling enthusiasts. Tackle iconic climbs like the Alpe d'Huez and Col de Sarenne, while enjoying breathtaking views of the surrounding mountains. This adventure is perfect for cyclists who are looking for a combination of thrilling ascents and unforgettable descents. Pedal through the same paths as the legendary Tour de France champions and test your endurance in one of the most beautiful cycling destinations in the world.",
        image: "/images/road-cycling.jpg",
        more: "https://cyclingholidaysfrance.com/tours/french-alps-cycling-tour/",
        id: 1,
        country: "France",
    },
    {
        title: "Mountain biking",
        price: "Changes",
        duration: "Your choice",
        difficulty: "Beginner to Moderate, Families",
        smallDescription: "Discover hundreds of miles of trails, all wrapped up in the most amazing scenery and served by a huge network of bike lifts.",
        description: "Mountain biking in the French Alps is a thrilling adventure with hundreds of miles of trails. Whether you're a beginner or a seasoned rider, you can enjoy spectacular landscapes while riding through forests, alpine meadows, and rugged mountain terrain. The region is known for its excellent network of bike lifts, ensuring easy access to the best trails. The mix of challenging and scenic routes offers something for riders of all levels, making it a perfect family-friendly activity.",
        image: "/images/mountain-biking.jpg",
        more: "https://www.alpineelements.co.uk/activity-holidays/france/morzine/mountain-biking",
        id: 2,
        country: "France",
    },
    {
        title: "Mountain fishing",
        price: "6€ - 80€",
        duration: "Your choice",
        difficulty: "All skill levels",
        smallDescription: "Fish in high-altitude lakes and rivers, surrounded by breathtaking alpine scenery.",
        description: "Mountain fishing in the French Alps provides an opportunity to experience the tranquility of high-altitude lakes and rivers. Surrounded by breathtaking alpine scenery, this peaceful activity allows anglers to catch trout and other fish in pristine waters. The quiet beauty of the mountain landscapes makes this a perfect escape for those seeking relaxation and a connection to nature. Whether you’re a beginner or an experienced angler, mountain fishing offers something special for everyone.",
        image: "/images/mountain-fishing.jpg",
        more: "https://en.france-montagnes.com/magazine/mountain-fishing-discovering-high-altitude-rivers-and-lakes",
        id: 3,
        country: "France",
    },
    {
        title: "Walking",
        price: "Changes",
        duration: "Your choice",
        difficulty: "Easy to Moderate",
        smallDescription: "Enjoy picturesque landscapes and charming villages on a walking holiday in the French Alps.",
        description: "Walking holidays in the French Alps are the perfect way to explore the stunning natural beauty of the region. Whether you’re wandering through charming villages or trekking along picturesque alpine trails, every step is filled with breathtaking views. The walking routes range from easy, leisurely walks to more challenging mountain hikes, so there’s something for all fitness levels. This is an ideal way to immerse yourself in the beauty and serenity of the Alps.",
        image: "/images/walking.jpg",
        more: "https://www.rambleworldwide.co.uk/europe/france",
        id: 4,
        country: "France",
    },
    {
        title: "Sailing",
        price: "Changes",
        duration: "1-2 weeks",
        difficulty: "Beginner to Advanced",
        smallDescription: "Learn the basics of sailing or explore alpine lakes on a unique sailing adventure.",
        description: "Sailing in the French Alps is a unique way to experience the mountains from a completely different perspective. Whether you’re a beginner learning the basics or an advanced sailor exploring crystal-clear alpine lakes, this adventure offers something for everyone. The tranquil waters of the lakes, surrounded by towering mountains, create a perfect backdrop for a sailing adventure. This is a perfect way to connect with nature while learning or improving your sailing skills.",
        image: "/images/sailing.jpg",
        more: "https://undiscoveredmountains.com/sailing-french-alps",
        id: 5,
        country: "France",
    },
    {
        title: "Base jumping",
        price: "1,500€/person",
        duration: "7/8 days",
        difficulty: "Expert",
        smallDescription: "Jump from some of the most thrilling locations in France, Italy, and Switzerland.",
        description: "Base jumping in the French Alps, Switzerland, and Italy is the ultimate thrill for adrenaline junkies. Leap from some of the most dramatic and breathtaking cliffs in Europe and experience the rush of freefall before deploying your parachute. This extreme sport is not for the faint of heart and requires expert skills and preparation. With stunning alpine landscapes as your backdrop, base jumping in these locations is an experience like no other, offering a true adrenaline rush in the most spectacular settings.",
        image: "/images/jumping.jpg",
        more: "https://nextlevel.ws/courses/apply/350",
        id: 6,
        country: "France, Italy, Switzerland",
    },
    {
        title: "White water rafting",
        price: "From 35€",
        duration: "Your choice",
        difficulty: "Beginner to Advanced",
        smallDescription: "Experience the thrill of navigating fast-moving alpine rivers.",
        description: "White water rafting in the French Alps is an exhilarating way to experience the region's stunning rivers. The rivers here offer fast-moving, thrilling rapids that provide the perfect setting for an adrenaline-pumping adventure. Whether you're a beginner or an expert, the variety of rapids ensures there's an option for everyone. Surrounded by the majestic mountain scenery, rafting through the French Alps is an unforgettable adventure that combines excitement with natural beauty.",
        image: "/images/water-rafting.jpg",
        more: "https://evolution2.com/en/rafting",
        id: 7,
        country: "France",
    },
    {
        title: "Rock climbing",
        price: "From 885€ to 936€",
        duration: "4 days",
        difficulty: "Intermediate to Advanced",
        smallDescription: "Climb some of the world's best limestone routes in the Southern French Alps.",
        description: "Rock climbing in the Southern French Alps is a dream for experienced climbers seeking a challenge in one of the most beautiful places in the world. The region is renowned for its world-class limestone climbing routes that test your technical skills and endurance. Whether you’re climbing classic routes or exploring more off-the-beaten-path areas, the scenery of the surrounding mountains adds to the thrill. With the guidance of expert instructors, you can take your climbing skills to the next level in this stunning alpine environment.",
        image: "/images/rock-climbing.jpg",
        more: "https://undiscoveredmountains.com/rock-climbing-weekend-french-alps-skills-adventure",
        id: 8,
        country: "France",
    },
    {
        title: "Paragliding",
        price: "140€ - 350€",
        duration: "20-40 minutes",
        difficulty: "Beginner to Advanced",
        smallDescription: "Soar over the Alps for a breathtaking bird’s-eye view of the mountains.",
        description: "Paragliding in the French Alps offers an exhilarating way to see the mountains from a bird’s-eye view. With professional pilots guiding you, you can soar over the alpine landscapes, enjoying breathtaking views of snow-capped peaks, alpine lakes, and lush valleys. Whether you're a first-timer or an experienced paraglider, this adventure gives you the opportunity to experience the Alps from a completely new perspective. The calm, scenic flights offer a peaceful and thrilling experience all at once.",
        image: "/images/paragliding.jpg",
        more: "https://www.fly-chamonix.com/",
        id: 9,
        country: "France",
    },
    {
        title: "Road cycling",
        price: "From 1,950€/person",
        duration: "6 days",
        difficulty: "Challenging",
        smallDescription: "Conquer the Swiss Alps with high-altitude climbs and scenic routes.",
        description: "Road cycling in the Swiss Alps is an extreme challenge for cyclists seeking to conquer high-altitude climbs and breathtaking routes. Ride through some of the most scenic and demanding roads, where the views of snow-covered peaks and mountain passes create a true sense of achievement. The challenging ascents are made even more rewarding by the thrilling descents and the spectacular landscapes that surround you. If you're up for a tough challenge, cycling through the Swiss Alps offers an unforgettable experience.",
        image: "/images/road-cycling-swiss.jpg",
        more: "https://marmot-tours.co.uk/holidays/road-cycling-holiday-swiss-alps",
        id: 10,
        country: "Switzerland",
    },
    {
        title: "Mountain biking",
        price: "Changes",
        duration: "Your choice",
        difficulty: "Beginner to Expert",
        smallDescription: "Enjoy world-class mountain biking trails with stunning Swiss landscapes.",
        description: "Mountain biking in the Swiss Alps offers an adrenaline-packed adventure through some of the world’s most scenic landscapes. Whether you're a beginner looking for easier trails or an expert seeking a technical challenge, the region offers trails for all skill levels. The routes wind through alpine meadows, dense forests, and rocky mountain passes, providing diverse terrain and spectacular views. The Swiss Alps are famous for their pristine trails, making it a top destination for mountain biking enthusiasts.",
        image: "/images/mountain-biking-swiss.jpg",
        more: "https://www.alpenwild.com/staticpage/swiss-alps/",
        id: 11,
        country: "Switzerland",
    },
    {
        title: "Walking",
        price: "Changes",
        duration: "Your choice",
        difficulty: "Easy to Challenging",
        smallDescription: "Explore serene alpine trails with breathtaking mountain views.",
        description: "Walking in the Swiss Alps offers an immersive experience in some of Europe’s most spectacular landscapes. Whether you’re walking along serene lakesides, through charming villages, or ascending alpine trails, the views are always breathtaking. From easy strolls to more challenging hikes, there’s something for every fitness level. With stunning mountain vistas, picturesque valleys, and alpine meadows, a walking holiday in the Swiss Alps is perfect for nature lovers and adventurers alike.",
        image: "/images/walking-swiss.jpeg",
        more: "https://www.macsadventure.com/walking-holiday/inspiration/alpine-treks/swiss-alps/",
        id: 12,
        country: "Switzerland",
    },
    {
        title: "Sailing",
        price: "Changes",
        duration: "1-2 weeks",
        difficulty: "Beginner to Advanced",
        smallDescription: "Sail across crystal-clear lakes in the heart of the Swiss Alps.",
        description: "Sailing in Switzerland offers the perfect combination of adventure and tranquility. Navigate crystal-clear alpine lakes surrounded by towering mountain peaks, creating a truly stunning environment. Whether you're learning the basics of sailing or already an experienced sailor, the Swiss lakes provide an ideal setting for all levels. The serene waters and breathtaking landscapes make sailing a peaceful and adventurous way to explore the Swiss Alps.",
        image: "/images/sailing-swiss.jpeg",
        more: "https://www.nautilusyachting.com/",
        id: 13,
        country: "Switzerland",
    },
    {
        title: "Base jumping",
        price: "Changes",
        duration: "Your choice",
        difficulty: "Expert",
        smallDescription: "Leap from breathtaking cliffs and experience the ultimate adrenaline rush.",
        description: "Base jumping in Switzerland is for thrill-seekers looking to experience the ultimate adrenaline rush. Leap from some of the most stunning cliffs in the world and enjoy an unforgettable freefall before deploying your parachute. The cliffs of Switzerland offer dramatic and breathtaking views, making this extreme sport one of the most exhilarating ways to connect with nature. This activity is for experts only, requiring proper training and preparation.",
        image: "/images/base-jumping-swiss.jpg",
        more: "https://nextlevel.ws/courses/apply/350",
        id: 14,
        country: "Switzerland",
    },
    {
        title: "White water rafting",
        price: "From 35€",
        duration: "Your choice",
        difficulty: "Beginner to Advanced",
        smallDescription: "Take on thrilling rapids in the stunning Swiss wilderness.",
        description: "White water rafting in Switzerland offers an action-packed adventure as you navigate the country's wild and fast-moving rivers. The Swiss wilderness provides the perfect backdrop for this thrilling activity, with rapids that range from beginner-friendly to extreme. Surrounded by towering mountains and pristine forests, the rafting experience offers an adrenaline rush while connecting you with nature. Whether you’re new to rafting or an experienced adventurer, Switzerland’s rivers are an unforgettable challenge.",
        image: "/images/rafting-swiss.jpeg",
        more: "https://evolution2.com/en/rafting",
        id: 15,
        country: "Switzerland",
    },
    {
        title: "Rock climbing",
        price: "Changes",
        duration: "Varies",
        difficulty: "Beginner to Advanced",
        smallDescription: "Climb some of Europe's most challenging rock faces in the Alps.",
        description: "Rock climbing in the Swiss Alps is an adventure for climbers of all levels. The Alps offer some of Europe’s most challenging rock faces, with routes that test your skills and provide incredible views. From beginner-friendly climbs to extreme technical routes, there's something for every climber. Whether you’re scaling a sheer rock wall or navigating a steep mountain face, the combination of thrilling climbs and stunning alpine scenery makes Swiss rock climbing an experience you won't forget.",
        image: "/images/rock-climbing-swiss.jpg",
        more: "https://www.alpenwild.com/staticpage/swiss-alps/",
        id: 16,
        country: "Switzerland",
    },
    {
        title: "Paragliding",
        price: "From 140€ - 350€",
        duration: "20-40 minutes",
        difficulty: "Beginner to Advanced",
        smallDescription: "Glide over the Swiss Alps for an unforgettable flying experience.",
        description: "Paragliding in the Swiss Alps offers a once-in-a-lifetime experience as you glide high above the stunning alpine landscapes. Whether you're a beginner or an experienced pilot, the region provides a variety of options to suit all levels. Soar over majestic peaks, lush valleys, and crystal-clear lakes, all while experiencing the thrill of free flight. The panoramic views of the Swiss Alps make this activity one of the most unforgettable ways to experience the beauty of the region.",
        image: "/images/paragliding-swiss.jpg",
        more: "https://www.getyourguide.com/en-gb/-l32356/-tc90/",
        id: 17,
        country: "Switzerland",
    }
]